# Generated by Django 3.1.3 on 2021-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210915_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='Submission',
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
