# Generated by Django 3.1.3 on 2021-09-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20210915_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.AddField(
            model_name='submission',
            name='choice_submit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinecourse.lesson'),
        ),
    ]
