# Generated by Django 3.1.3 on 2021-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20210916_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='lesson',
        ),
        migrations.AddField(
            model_name='submission',
            name='choice',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='choice_submit',
            field=models.IntegerField(null=True),
        ),
    ]
