# Generated by Django 3.1.3 on 2021-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20210916_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='choice_submit',
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
