# Generated by Django 3.1.3 on 2021-09-17 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0009_submission_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
