# Generated by Django 3.1.3 on 2021-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0010_auto_20210917_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_choice',
            field=models.ManyToManyField(related_name='choices', through='onlinecourse.Choice', to='onlinecourse.Lesson'),
        ),
    ]
