# Generated by Django 3.1.3 on 2021-09-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0011_question_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_submit',
            field=models.ManyToManyField(related_name='choices', through='onlinecourse.Submission', to='onlinecourse.Question'),
        ),
        migrations.AddField(
            model_name='submission',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinecourse.choice'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='onlinecourse.question'),
        ),
    ]
