# Generated by Django 3.1.3 on 2021-09-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0012_auto_20210917_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_submit',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='choice',
        ),
    ]
