# Generated by Django 3.1.3 on 2021-09-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0013_auto_20210917_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_choice',
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(null=True, to='onlinecourse.Choice'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
