# Generated by Django 3.1.3 on 2021-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0014_auto_20210917_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(blank=True, to='onlinecourse.Choice'),
        ),
    ]
