# Generated by Django 3.1.3 on 2021-09-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0016_remove_submission_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
    ]
