# Generated by Django 3.1.3 on 2021-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0023_auto_20210918_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_for_choice',
            field=models.ManyToManyField(related_name='question_submitted', to='onlinecourse.Choice'),
        ),
    ]
