# Generated by Django 3.1.3 on 2021-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0024_question_question_for_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_for_choice',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_submitted',
            field=models.ManyToManyField(editable=False, to='onlinecourse.Submission'),
        ),
    ]
