# Generated by Django 3.1.3 on 2021-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0026_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lesson_id',
            field=models.IntegerField(null=True),
        ),
    ]
